version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-timesheet
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: timesheetdb
    ports:
      - "3306:3306"
    volumes:
      - timesheetvol:/var/lib/mysql

  timesheet:
    image: timesheet-derouichemohamedaziz-4nids
    container_name: timesheet-app
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/timesheetdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass

volumes:
  timesheetvol:
